language: python
python:
  - "3.3"
env:
  - DJANGO_VERSION=1.6
install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install -q -e . --use-mirrors
  - python setup.py -q install
script:
  - python setup.py test
